#!/usr/bin/env node
"use strict";

var _tape = require("tape");

var _tape2 = _interopRequireDefault(_tape);

var _bufferEqual = require("buffer-equal");

var _bufferEqual2 = _interopRequireDefault(_bufferEqual);

var _WebSocketFrame = require("../../lib/WebSocketFrame");

var _utils = require("../../lib/utils");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var bufferAllocUnsafe = _utils.bufferAllocUnsafe;
var bufferFromString = _utils.bufferFromString;

(0, _tape2.default)('Serializing a WebSocket Frame with no data', function (t) {
  t.plan(2);

  // WebSocketFrame uses a per-connection buffer for the mask bytes
  // and the frame header to avoid allocating tons of small chunks of RAM.
  var maskBytesBuffer = bufferAllocUnsafe(4);
  var frameHeaderBuffer = bufferAllocUnsafe(10);

  var frameBytes;
  var frame = new _WebSocketFrame.WebSocketFrame(maskBytesBuffer, frameHeaderBuffer, {});
  frame.fin = true;
  frame.mask = true;
  frame.opcode = 0x09; // WebSocketFrame.PING
  t.doesNotThrow(function () {
    frameBytes = frame.toBuffer(true);
  }, 'should not throw an error');

  t.assert((0, _bufferEqual2.default)(frameBytes, bufferFromString('898000000000', 'hex')), 'Generated bytes should be correct');

  t.end();
});